#!/bin/bash
pr --number-lines --omit-header --omit-pagination wash.tcl|\
enscript --silent --no-header --highlight=tcl --no-job-header --portrait\
    --color --language=html --output wash.html\
    --title=wash.tcl

tclsh wash.tcl > wash_run.txt 2>&1

pr --number-lines --omit-header --omit-pagination wash_run.txt |\
enscript --silent --no-header --no-job-header --portrait\
    --language=html --output wash_run.html\
    --title=wash_run.txt
