#!/bin/bash
source-highlight --input=wash.tcl --output=wash.html --doc\
    --title="Washing Machine Source" --line-number=" "

tclsh wash.tcl > wash_run.txt 2>&1

pr --number-lines --omit-header --omit-pagination wash_run.txt |\
enscript --silent --no-header --no-job-header --portrait\
    --language=html --output wash_run.html\
    --title=wash_run.txt
