# DO NOT EDIT THIS FILE!
# THIS FILE IS AUTOMATICALLY GENERATED FROM A LITERATE PROGRAM SOURCE FILE.
#
# This software is copyrighted 2015 by G. Andrew Mangogna.
# The following terms apply to all files associated with the software unless
# explicitly disclaimed in individual files.
# 
# The authors hereby grant permission to use, copy, modify, distribute,
# and license this software and its documentation for any purpose, provided
# that existing copyright notices are retained in all copies and that this
# notice is included verbatim in any distributions. No written agreement,
# license, or royalty fee is required for any of the authorized uses.
# Modifications to this software may be copyrighted by their authors and
# need not follow the licensing terms described here, provided that the
# new terms are clearly indicated on the first page of each file where
# they apply.
# 
# IN NO EVENT SHALL THE AUTHORS OR DISTRIBUTORS BE LIABLE TO ANY PARTY FOR
# DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING
# OUT OF THE USE OF THIS SOFTWARE, ITS DOCUMENTATION, OR ANY DERIVATIVES
# THEREOF, EVEN IF THE AUTHORS HAVE BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE AUTHORS AND DISTRIBUTORS SPECIFICALLY DISCLAIM ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.  THIS SOFTWARE
# IS PROVIDED ON AN "AS IS" BASIS, AND THE AUTHORS AND DISTRIBUTORS HAVE
# NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS,
# OR MODIFICATIONS.
# 
# GOVERNMENT USE: If you are acquiring this software on behalf of the
# U.S. government, the Government shall have only "Restricted Rights"
# in the software and related documentation as defined in the Federal
# Acquisition Regulations (FARs) in Clause 52.227.19 (c) (2).  If you
# are acquiring the software on behalf of the Department of Defense,
# the software shall be classified as "Commercial Computer Software"
# and the Government shall have only "Restricted Rights" as defined in
# Clause 252.227-7013 (c) (1) of DFARs.  Notwithstanding the foregoing,
# the authors grant the U.S. Government and others acting in its behalf
# permission to use and distribute the software in accordance with the
# terms specified in this license.

domain bookstore {
    set producttag 100 ; # <1>
    set eumlid 780201
    set recid 7789930
    set wordid 938763
    class Product {
        productID
        productName
        copyright
        unitPrice
        description
        website 
        currentlyAvailable
        categoryID
        groupCode
        publisherCode
    }\
        $eumlid\
        {Executable UML: A Foundation for Model-Driven Architecture}\
        2002\
        2995\
        {Book on software development using models.}\
        www.executableumlbook.com\
        true\
        [set bookid [incr categorytag]]\
        0\
        201\
    \
        $recid\
        {Carnival Music for Children}\
        1955\
        1000\
        {Music as heard at old time carnivals}\
        {}\
        true\
        [set musicid [incr categorytag]]\
        1\
        523\
    \
        $wordid\
        {Word 2020 for MacOSX}\
        2020\
        5995\
        {Infamous word processing program}\
        www.microsoft.com\
        true\
        [set swid [incr categorytag]]\
        2\
        666 ; # <1>
    class Publisher {
        groupCode
        publisherCode
        name
        address
        website
    } {
        0
        201
        Addison-Wesley
        {New York, NY}
        www.aw.com
    
        1
        523
        {Old-Time Music}
        {St. Louis, MO}
        www.otm.com
    
        2
        666
        {Microsoft, Inc.}
        {Seattle, WA}
        www.microsoft.com
    } ; # <1>
    class Author {
        name
        website
        email
    } {
        {Stephen J. Mellor}
        stephenmellor.com
        stephen@stephenmellor.com
    
        {Marc J. Balcer}
        marcbalcer.com
        marc@marcbalcer.com
    }
    class Authorship {
        name
        productID
        previousName
        previousProductID
    }\
        {Stephen J. Mellor}\
        $eumlid\
        {}\
        {}\
    \
        {Marc J. Balcer}\
        $eumlid\
        {Stephen J. Mellor}\
        $eumlid
    class BookProduct {
        productID
        bookNumber
        titleCode
        title
        subtitle
    }\
        $eumlid\
        {ISBN 0-201-74804-5}\
        74804-5\
        {Executable UML}\
        {A Foundation for Model-Driven Architecture}
    class RecordingProduct {
        productID
        runningTime
        recordingID
        formatID
    }\
        $recid\
        3:23\
        [set cmusid [incr recordingtag]]\
        [set cdid [incr formattag]]
    class SoftwareProduct {
        productID
        productVersion
        softwareID
        platformID
    }\
        $wordid\
        20.17.3\
        [set softid [incr softwaretag]]\
        [set platformid [incr platformtag]]
    class SpecialOrderProduct {
        productID
        specialOrderInstructions
        daysToDeliver
    }\
        $recid\
        {Their part number: 30557}\
        10
    class StockedProduct {
        productID
        quantityOnHand
        reorderThreshold
        reorderIncrement
        reorderInstructions
    }\
        $eumlid\
        100\
        200\
        100\
        {Ship as quickly as possible}\
    \
        $wordid\
        55\
        25\
        55\
        {Get a discount}
    class ProductCategory {
        categoryID
        categoryName
        parentCategoryID
    }\
        $bookid\
        book\
        {}\
    \
        $musicid\
        music\
        {}\
    \
        $swid\
        software\
        {}
    class Recording {
        recordingID
        title
    }\
        $cmusid\
        {Carnival Music for Children}
    class Artist {
        artistID
        artistName
    }\
        [set artist1id [incr artisttag]]\
        {Mary Jane}\
    \
        [set artist2id [incr artisttag]]\
        {Fred Smith}
    class PerformanceCredit {
        recordingID
        artistID
        prevRecordingID
        prevArtistID
    }\
        $cmusid\
        $artist1id\
        {}\
        {}\
    \
        $cmusid\
        $artist2id\
        $cmusid\
        $artist1id
    class RecordingFormat {
        formatID
        formatName
    }\
        $cdid\
        CD
    class Platform {
        platformID
        platformName
    }\
        $platformid\
        MacOSX
    class ComputerSoftware {
        softwareID
        title
    }\
        $softid\
        {Word 2020 for MacOSX}
    class ShippingCompany {
        companyName
        trackingWebsite
        customerServicePhone
        localDispatchPhone
        localOffice
        localContact
    } {
        FedEx
        www.fedex.com
        222-555-1212
        223-555-1212
        {200 Elm St., Anywhere, CA 94000}
        {George Shipper}
    
        UPS
        www.ups.com
        224-555-1212
        225-555-1212
        {220 Elm St., Anywhere, CA 94000}
        {John Parcel}
    }
    class Warehouse {
        warehouseName
        warehouseLocation
    } {
        {Acme Bookstore Warehouse}
        {100 Broad St., Somewhere, CA 94000}
    
        {My Fulfillment}
        {100 Fremont St., Somewhere, CA 94000}
    }
    class WarehouseClerk {
        clerkID
        clerkName
        warehouseName
    }\
        [set clerk1id [incr clerktag]]\
        {Fred Smith}\
        {Acme Bookstore Warehouse}\
    \
        [set clerk2id [incr clerktag]]\
        {John Industrious}\
        {Acme Bookstore Warehouse}\
    \
        [set clerk3id [incr clerktag]]\
        {George Slacker}\
        {My Fulfillment}
    class ShippingClerk {
        clerkID
    }\
        $clerk1id
    class StockClerk {
        clerkID
    }\
        $clerk2id
    class OffDutyClerk {
        clerkID
    }\
        $clerk3id
}
